config/routes.rb
Rails.application.routes.draw do
  root to: 'pages#home'
  devise_for :users
  resources :bikes do
    resources :bookings, only: [:new, :create, :edit, :update, :show]
  end
  resources :bookings, only: [:destroy] do
    resources :reviews, only: [:new, :create]
  end

  resources :dashboard, only: [:index]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bike.rb
class Bike < ApplicationRecord
  belongs_to :user
  has_many :bookings, dependent: :destroy
  has_many :reviews, through: :bookings
  has_many_attached :photos
  validates :title, :price, :photos, presence: true
  validates :title, uniqueness: true
  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?

  CATEGORIES = ["Dutch", "Electric", "Racing", "BMX", "Road", "Mountain", "Tandem", "Cruiser", "Single Speed", "Track"]
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :user
  belongs_to :bike
  has_one :review, dependent: :destroy
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :booking

  validates :content, :rating, presence:true
  validates :rating, inclusion: { in: 0..5 }, numericality: { only_integer: true }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :bikes, dependent: :destroy
  has_many :bookings, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bikes_controller.rb
class BikesController < ApplicationController
  before_action :set_bike, only: [:show, :edit, :update, :destroy, :address]

  def index
    if params[:query].present?
      @bikes = Bike.where(title: params[:query])
    else
      @bikes = Bike.all
    end

    @bikes= Bike.geocoded # returns flats with coordinates

    @markers = @bikes.map do |bike|
      {
        lat: bike.latitude,
        lng: bike.longitude,
        infoWindow: render_to_string(partial: "info_window", locals: { bike: bike })
      }
    end
  end

  def show
    @markers =
      [{
        lat: @bike.latitude,
        lng: @bike.longitude,
        infoWindow: render_to_string(partial: "info_window", locals: { bike: @bike })
      }]
  end

  def new
    @bike = Bike.new
  end

  def create
    @bike = Bike.new(bike_params)
    @bike.user = current_user
    if @bike.save!
      redirect_to bike_path(@bike)
    else
      render :new
    end
  end

  def edit;
  @bike = Bike.find(params[:id])
  end

  def update
    if @bike.update(bike_params)
      redirect_to bike_path(@bike)
    else
      render :edit
    end
  end

  def destroy
    @bike = Bike.find(params[:id])
    @bike.destroy
    redirect_to bikes_path, notice: 'The bike was successfully destroyed.'
  end

  private

  def set_bike
    @bike = Bike.find(params[:id])
  end

  def bike_params
    params.require(:bike).permit(:category, :location,  :address, :price, :title, :lat, :long, photos: [])
  end
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
   before_action :set_booking, only: [:edit, :update, :destroy]

  def show
    @booking = Booking.find(params[:id])
  end

  def new
    @bike = Bike.find(params[:bike_id])
    @booking = Booking.new
  end

  def create
    @bike = Bike.find(params[:bike_id])

    @booking = Booking.new(booking_params)
    @booking.bike = @bike
    @booking.user = current_user
    @booking.total_price = (@booking.end_date - @booking.start_date) * @bike.price
    if @booking.save
      redirect_to bike_booking_path(@bike, @booking)
    else
      render :new
    end
  end

  def edit
    @booking = Booking.find(params[:id])
  end

  def update
    @bike = Bike.find(params[:bike_id])
    @booking.update(booking_params)
    @booking.bike = @bike
    redirect_to dashboard_index_path
  end

 def destroy
    @booking = Booking.find(params[:id])
    @bike = Bike.find(@booking.bike_id)
    @booking.destroy
    redirect_to dashboard_index_path
  end

  private

  def set_booking
    @booking = Booking.find(params[:id])
  end

  def booking_params
    params.require(:booking).permit(:start_date, :end_date, :total_price)
  end
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  def index
    @bookings = Booking.all
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  def new
    @booking = Booking.find(params[:booking_id])
    @review = Review.new
  end

  def create
    @booking = Booking.find(params[:booking_id])
    @review = Review.new(review_params)
    # Associate my review together with my booking
    @review.booking = @booking
    if @review.save
      # success
      redirect_to bike_path(@booking.bike_id, anchor: "review-#{@review.id}")
    else
      # failure
      render 'bikes/show'
    end
  end

  private

  def review_params
    params.require(:review).permit(:content, :rating)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bikes/_form.html.erb
<div class="container">
  <%= simple_form_for [ @bike ] do |f| %>
    <%= f.input :title %>
    <%= f.input :category, collection: ["Dutch", "Electric", "Racing", "BMX", "Road", "Mountain", "Tandem", "Cruiser", "Single Speed", "Track"] %>
    <%= f.input :location %>
    <%= f.input :address %>
    <%= f.input :price %>
    <%= f.input :photos, as: :file, input_html: { multiple: true } %>
    <%= f.submit "Add bike", class: "btn btn-outline-primary" %>
  <% end %>
</div>

app/views/bikes/_info_window.html.erb
<h3><%= bike.title %></h3>
<p><%= bike.address %></p>

app/views/bikes/edit.html.erb
<div class="container mt-5">
  <h1 class="title">Edit a bike</h1>
  <%=  render 'form' %>

   <div class= "m-3">
  <%= link_to 'Back', bikes_path, class: "btn btn-outline-primary btn-sm" %>
  </div>
</div>

app/views/bikes/index.html.erb
<div class="container mt-5" style="align-items: center;">
  <h1 class="title">Bikes</h1>
  <p class="text-right">add a bike <span><%= link_to "<i class='fas fa-plus'></i>".html_safe, new_bike_path %></span></p>
  <div class="m-5" id="map"
    style="width: 90%; height:500px;"
    data-markers="<%= @markers.to_json %>"
    data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>">
  </div>
  <div class="row card-group">
    <% @bikes.each do |bike| %>
    <div class="col-4">
      <div class="card m-2" style="width: 16rem;">
        <div id="<%= 'carousel' + bike.id.to_s %>" class="carousel slide" data-ride="carousel" data-interval="10000">
          <ol class="carousel-indicators">
            <% bike.photos.each_with_index do |photo, idx|  %>
            <li data-target="#<%= 'carousel' + bike.id.to_s %>" data-slide-to="<%= idx %>" class="<%='active' if idx == 0 %>"></li>
            <% end %>
          </ol>
          <div class="carousel-inner">
            <% bike.photos.each_with_index do |photo, idx|  %>
            <div class="carousel-item <%= 'active' if idx == 0  %>">
              <div class="card-category_pic" style="background-image: url('<%= cl_image_path bike.photos[idx].key %>')">
              </div>
            </div>
            <% end %>
          </div>
          <a class="carousel-control-prev" href="#<%= 'carousel' + bike.id.to_s %>" role="button" data-slide="prev">
            <span class="carousel-control-prev-icon" aria-hidden="true"></span>
            <span class="sr-only">Previous</span>
          </a>
          <a class="carousel-control-next" href="#<%= 'carousel' + bike.id.to_s %>" role="button" data-slide="next">
            <span class="carousel-control-next-icon" aria-hidden="true"></span>
            <span class="sr-only">Next</span>
          </a>
        </div>
        <div class="card-body">
          <h5 class="card-title"><%= link_to bike.title, bike_path(bike) %></h5>
          <p class="card-text">Bike Category: <%= bike.category %></p>
          <p class="card-text">Location: <%= bike.location %></p>
          <p class="card-text">Price: €<%= bike.price %></p>
          <p class="card-text"><small class="text-muted">bike-match ❤️</small></p>
        </div>
      </div>
    </div>
    <% end %>
  </div>
</div>

app/views/bikes/new.html.erb
<div class="container mt-5">
  <h1 class="title">Add a bike</h1>
  <%=  render 'form' %>

  <div class= "m-3">
  <%= link_to 'Back', bikes_path, class: "btn btn-outline-primary btn-sm" %>
  </div>
</div>

app/views/bikes/show.html.erb
<div class="container">
    <p class="text-right mt-5">Edit this bike <span><%= link_to "<i class='fas fa-pencil-alt'></i>".html_safe, edit_bike_path %></span></p>
    <p class="text-right">Delete this bike <span><%= link_to "<i class='far fa-trash-alt'></i>".html_safe, bike_path, method: :delete, data: {confirm: 'Are you sure?'} %></span></p>
  <div class="justify-content-center align-items-center">
    <div class="row">
      <div class="col-4">
        <div class="card-container">
          <div class="card mt-2" style="width: 18rem;">
            <div id="<%= 'carousel' + @bike.id.to_s %>" class="carousel slide" data-ride="carousel" data-interval="10000">
              <ol class="carousel-indicators">
                <% @bike.photos.each_with_index do |photo, idx|  %>
                  <li data-target="#<%= 'carousel' + @bike.id.to_s %>" data-slide-to="0" class="active"></li>
                <% end %>
              </ol>
                <div class="carousel-inner">
                  <% @bike.photos.each_with_index do |photo, idx|  %>
                    <div class="carousel-item <%= 'active' if idx == 0  %>">
                      <div class="card-category_pic" style="background-image: url('<%= cl_image_path @bike.photos[idx].key %>')">
                      </div>
                    </div>
                  <% end %>
                <a class="carousel-control-prev" href="#<%= 'carousel' + @bike.id.to_s %>" role="button" data-slide="prev">
                  <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                  <span class="sr-only">Previous</span>
                </a>
                <a class="carousel-control-next" href="#<%= 'carousel' + @bike.id.to_s %>" role="button" data-slide="next">
                  <span class="carousel-control-next-icon" aria-hidden="true"></span>
                  <span class="sr-only">Next</span>
                </a>
              </div>
            </div>
            <div class="card-body">
              <h5 class="card-title"><%= @bike.title %></h5>
            </div>
            <ul class="list-group list-group-flush">
              <li class="list-group-item">Price: €<%= @bike.price %></li>
              <li class="list-group-item">Type of Bike: <%= @bike.category %></li>
              <li class="list-group-item">Location: <%= @bike.location %></li>
            </ul>
            <div class="card-body text-center">
              <%= link_to "Book this bike now!", new_bike_booking_path(@bike), class: "btn btn-outline-primary" %>
            </div>
          </div>
        </div>
      </div>

      <div class="col-8 mt-2">
        <div id="map"
        style="width: 100%; height: 484px;"
        data-markers="<%= @markers.to_json %>"
        data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>">
        </div>
      </div>
     </div>

  <div class="row">
    <div class="col-12">
      <h2 class="title text-center my-5">Reviews For <%= @bike.title %></h2>
        <ul>
          <% @bike.reviews.each do |review| %>
            <li>
              <div class="card mt-3">
                <div class="card-header">
                  <% review.rating.to_i.times do  %>
                   <span class="star"><i class="fas fa-star"></i></span>
                  <% end %>
                </div>
                <div class="card-body">
                  <blockquote class="blockquote mb-0">
                    <p><%= review.content %></p>
                    <footer class="blockquote-footer"><%= @bike.title %> Customer</footer>
                  </blockquote>
                </div>
              </div>
            </li>
          <% end %>
        </ul>
      </div>
    </div>
  </div>
</div>

app/views/bookings/_form.html.erb
<div class="row">
  <div class="container">
    <%= simple_form_for [@bike, @booking] do |f| %>
      <%= f.input :start_date, as: :string, input_html: {class: "datepicker"}%>
      <%= f.input :end_date, as: :string, input_html: {class: "datepicker", id: "secondRangeInput"}%>
      <%= f.submit "Make Booking", class: "btn btn-outline-primary btn-rounded btn-sm my-0" %>
    <% end %>
  </div>
</div>

app/views/bookings/edit.html.erb
<div class="container mt-5">
  <%= simple_form_for [ @booking ] do |f| %>
    <%= f.input :start_date %>
    <%= f.input :end_date %>
    <%= f.submit "Edit booking", class: "btn btn-outline-primary" %>
  <% end %>
  <%= link_to "Delete this booking",
            bike_path(@booking),
            method: :delete,
            data: { confirm: "Are you sure?" }, class: "btn btn-outline-primary btn-sm mt-3" %>
  <div>
    <%= link_to 'Back', bikes_path, class: "btn btn-outline-primary btn-sm mt-3"%>
  </div>
</div>

app/views/bookings/new.html.erb
<div class="container mt-5">
  <h1 class="title">Make new booking</h1>
  <%=  render 'form', bike:@bike %>

  <div class= "mt-3">
  <%= link_to 'Back', bikes_path(@bike), class: "btn btn-outline-primary btn-sm" %>
  </div>
</div>

app/views/bookings/show.html.erb
<div class="container mt-5 text-center" >
  <h1 class="title">Booking Confirmation</h1>
  <p>Thanks for booking with Bike Match!</p>
  <div class="mt-5">
    <p>Start Date is:   <%= @booking.start_date %></p>
    <p>End Date is:     <%= @booking.end_date %></p>
    <p>Open Balance:    €<%= @booking.total_price %></p>
  </div>
  <%= link_to "See all your bookings", dashboard_index_path(@bike), class: "btn btn-outline-primary" %>
</div>

app/views/dashboard/index.html.erb
<div class="container mt-5">
  <h1 class="title">Dashboard</h1>

  <% if user_signed_in? %>
  <div class="mt-3 mb-5">
    <p class="text-center">Here are your bookings:</p>
  </div>
  <div class="row card-group">
    <% @my_bookings = @bookings.select do |booking| %>
    <% booking.user == current_user %>
    <% end %>
    <% @my_bookings.each do |my_booking| %>
    <div class="col-4 mb-3">
      <div class="card" style="width: 18rem;">
        <div class="card-category_pic" style="background-image: url('<%= cl_image_path my_booking.bike.photos.first.key %>')">
        </div>
        <div class="card-body">
          <h5 class="card-title"><%= my_booking.bike.title %></h5>
          <p class="card-text"></p>
          <ul class="list-group list-group-flush">
            <li class="list-group-item">Start Date: <%= my_booking.start_date %></li>
            <li class="list-group-item">End Date: <%= my_booking.end_date %></li>
            <li class="list-group-item">Total Price: €<%= my_booking.total_price %></li>
            <li><p class="text-right mt-3">Edit this booking <span><%= link_to "<i class='fas fa-pencil-alt'></i>".html_safe, dashboard_index_path %></span></p></li>
            <li><p class="text-right">Delete this booking <span><%= link_to "<i class='far fa-trash-alt'></i>".html_safe,  booking_path(my_booking), method: :delete, data: {confirm: 'Are you sure?'} %></span></p></li>
            <li><p class="text-right pt-3 mb-0 border-top">Review this bike <span><%= link_to "<i class='fas fa-bicycle'></i>".html_safe, new_booking_review_path(my_booking) %></span></p></li>
          </ul>
        </div>
      </div>
    </div>
    <% end %>
  </div>
  <% else %>
  <p>Sorry you are not signed in- please sign in to see your bookings!</p>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>BikeMatch</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>
  <link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@300&family=Shrikhand&display=swap" rel="stylesheet">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

  <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
</head>

<body>
  <div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
    <!-- This link is for the bike icon may need to change not sure it works on heroku -->
    <a class="navbar-brand" href="/">
      <img style="width: 40px" src="https://static.thenounproject.com/png/1026671-200.png" />
    </a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>


    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item">
          <%= link_to "Bike Match", root_path, class: "nav-link logo-text mt-1" %>
        </li>
        <li class="nav-item">
          <%= link_to "Bikes", bikes_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Dashboard", dashboard_index_path, class: "nav-link" %>
        </li>
        <li class="nav-item dropdown">
          <img class="avatar dropdown-toggle" id="navbarDropdown" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" src="https://thumbor.forbes.com/thumbor/fit-in/416x416/filters%3Aformat%28jpg%29/https%3A%2F%2Fspecials-images.forbesimg.com%2Fimageserve%2F5e6e696937d0440006bc7c4c%2F0x0.jpg%3Fbackground%3D000000%26cropX1%3D0%26cropX2%3D3430%26cropY1%3D103%26cropY2%3D3535" />
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
           <%= link_to "sign in", new_user_session_path, class: "dropdown-item" %>
           <%= link_to "sign out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
         </div>
       </li>
     </ul>
   </div>
 </div>

 <div class="banner" style="background-image: url('https://images.unsplash.com/photo-1574904937426-89a94e79012c?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=700&q=60')">
  <div class="container">
    <h1 class="banner-text">Bike Match</h1>
    <h1 class="banner-text">Whatever your need is, find a bike that fits you!</h1>
  </div>
</div>

<%= yield %>
</div>
<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>
<div class="footer">
  <div class="footer-links">
    <a href="#"><i class="fab fa-instagram"></i></a>
    <a href="#"><i class="fab fa-facebook"></i></a>
    <a href="#"><i class="fab fa-twitter"></i></a>
  </div>
  <div class="footer-copyright">
    Made with <i class="fas fa-heart"></i> at Bike Match 2020
  </div>
</div>
</body>
</html>

app/views/pages/home.html.erb
<div class="container mt-5">
  <h1 class="title text-center">Find A Bike Near You!</h1>
  <div class= "d-flex justify-content-center align-items-center my-3">
    <%= form_tag bikes_path, method: :get do %>
    <%= text_field_tag :query,
      params[:query],
      class: "form-control",
      placeholder: "Find a bike"
    %>
    <%= submit_tag "Search", class: "btn btn-outline-primary m-3 ml-5 btn-lg" %>
    <% end %>
  </div>

  <div class="card-group">
    <div class="card m-2">
      <img src="https://images.pexels.com/photos/2591990/pexels-photo-2591990.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=750&w=1260" class="card-img-top" alt="...">
      <div class="card-body">
        <h5 class="card-title">Mountain bike</h5>
        <p class="card-text">Berlin Kreuzberg - 12€ - Available now</p>
      </div>
    </div>
    <div class="card m-2">
      <img src="https://images.pexels.com/photos/957157/pexels-photo-957157.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=750&w=1260" class="card-img-top" alt="...">
      <div class="card-body">
        <h5 class="card-title">Cargo bike</h5>
        <p class="card-text">Berlin Neukölln - 20€ - Available now</p>
      </div>
    </div>
    <div class="card m-2">
      <img src="https://images.pexels.com/photos/545004/pexels-photo-545004.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=750&w=1260" class="card-img-top" alt="...">
      <div class="card-body">
        <h5 class="card-title">Road bike</h5>
        <p class="card-text">Berlin Mitte - 10€ - Available now</p>
      </div>
    </div>
  </div>
</div>

app/views/pages/index.html.erb
<h1>Bikes</h1>

<ul>
  <% @bikes.each do |bike|%>
    <li><%= link_to bike.title, bike_path(bike) %></li>
  <% end %>
</ul>

app/views/reviews/new.html.erb
<div class="container mt-5">
  <h1 class="title">Write a review for <%= @booking.bike.title %></h1>

  <%= simple_form_for([@booking, @review]) do |f| %>
    <%= f.input :content %>
    <%= f.input :rating %>
    <%= f.submit class: "btn btn-outline-primary btn-sm" %>
  <% end %>

  <div class= "mt-3">
    <%= link_to 'Back', dashboard_index_path, class: "btn btn-outline-primary btn-sm" %>
  </div>
</div>